import Head from "next/head";
import Layout from "../components/Layout/Layout";
import styles from "../styles/Home.module.scss";
import { NextPage } from "next";
import client from "../client";
import Link from "next/link";

// type Post = {
//   title:string
// }

interface Props {
  userAgent?: string;
}

const Home: NextPage<Props> = (props) => {
  return (
    <div>
      <Head>
        <title>MrFarhan Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>MrFarhan's Blog</main>
        <ul>
          {Object.values(props).map((item, index) => {
            return (
              <Link href="/post/[slug]" as={`/post/${item?.slug?.current}`}>
                <a>{item?.title}</a>
              </Link>
            );
          })}
        </ul>
      </Layout>
    </div>
  );
};

Home.getInitialProps = async function (context) {
  // It's important to default the slug so that it doesn't return "undefined"
  const { slug = "" } = context.query;
  return await client.fetch(
    `
    *[_type == "post"]
  `,
    { slug }
  );
};

export default Home;
